version: '3'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres_local
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=may-the-fourth
    restart: unless-stopped
    volumes:
      - postgres_data:/bitnami/postgresql
      - ./create.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynet
        
  api:
    build:
      context: .
    container_name: api_local
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - mynet
        
  nginx:
    image: nginx:stable-alpine-slim
    container_name: nginx_local
    restart: unless-stopped
    volumes:
      - ./nginx.local.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:80"
    depends_on:
      - api
    networks:
      - mynet
        
  redis:
    image: redis:latest
    container_name: redis_local
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - mynet
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
    
networks:
  mynet:
    driver: bridge